# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sample_dcsbm_cpp <- function(z, Pmat, theta) {
    .Call(`_nett_sample_dcsbm_cpp`, z, Pmat, theta)
}

sample_r1 <- function(theta, p = 1) {
    .Call(`_nett_sample_r1`, theta, p)
}

