# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pair_dist2 <- function(x, y) {
    .Call(`_nett_pair_dist2`, x, y)
}

pair_dist2_mat <- function(z) {
    .Call(`_nett_pair_dist2_mat`, z)
}

sample_dclvm_cpp <- function(z, scale, theta) {
    .Call(`_nett_sample_dclvm_cpp`, z, scale, theta)
}

sample_dcer_cpp <- function(theta) {
    .Call(`_nett_sample_dcer_cpp`, theta)
}

sample_dcsbm_cpp <- function(z, Pmat, theta) {
    .Call(`_nett_sample_dcsbm_cpp`, z, Pmat, theta)
}

sample_r1 <- function(theta, p = 1) {
    .Call(`_nett_sample_r1`, theta, p)
}

